DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'vfsuser') THEN
    CREATE USER vfsuser WITH PASSWORD 'vfspass';
  END IF;
END $$;
GRANT ALL PRIVILEGES ON DATABASE vfsdb TO vfsuser;
GRANT ALL ON SCHEMA public TO vfsuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vfsuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO vfsuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO vfsuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO vfsuser;
