FROM mcr.microsoft.com/playwright:v1.44.0-jammy

WORKDIR /app

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/ms-playwright/chromium-1117/chrome-linux/chrome

COPY package.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY . .

RUN mkdir -p /app/sessions

EXPOSE 3001

CMD ["npm", "run", "dev"]
