export const WS_EVENTS = {
  // Server → Client
  SLOT_DETECTED: 'SLOT_DETECTED',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_FAILED: 'BOOKING_FAILED',
  BOOKING_PROGRESS: 'BOOKING_PROGRESS',
  CAPTCHA_REQUIRED: 'CAPTCHA_REQUIRED',
  LOG_ENTRY: 'LOG_ENTRY',
  MONITOR_STATUS: 'MONITOR_STATUS',

  // Client → Server
  CAPTCHA_SOLVED: 'CAPTCHA_SOLVED',
} as const;
